stages:
  prepare_data:
    cmd: python src/data/prepare_data.py
    deps:
    - src/data/prepare_data.py
    outs:
    - data/processed/test.npz
    - data/processed/train.npz
  train_model:
    cmd: python src/data/train_model.py
    deps:
    - data/processed/test.npz
    - data/processed/train.npz
    - src/data/train_model.py
    outs:
    - models/cifar10_model.h5
