stages:
  prepare_data:
    cmd: python src/data/prepare_data.py
    deps:
      - src/data/prepare_data.py
    outs:
      - data/processed

  train_model:
    cmd: python src/train/train_model.py
    deps:
      - src/train/train_model.py
      - data/processed/train.npz
      - data/processed/test.npz
    outs:
      - models/cifar10_model.h5
